[jobs.lab1]

image = { source = "dockerfile", path = ".", tag = "pascal-lex-example" }

run = [
  "export CLASSPATH='./antlr-4.9-complete.jar:$CLASSPATH'",
  "java Main $input $ir",
]

[jobs.lab2]

image = { source = "dockerfile", path = ".", tag = "pascal-lex-example" }

run = [
  "export CLASSPATH='./antlr-4.9-complete.jar:$CLASSPATH'",
  "java Main $input $ir",
]

[jobs.lab3]

image = { source = "dockerfile", path = ".", tag = "pascal-lex-example" }

run = [
  "export CLASSPATH='./antlr-4.9-complete.jar:$CLASSPATH'",
  "java Main $input $ir",
]

[jobs.lab4]

image = { source = "dockerfile", path = ".", tag = "pascal-lex-example" }

run = [
  "export CLASSPATH='./antlr-4.9-complete.jar:$CLASSPATH'",
  "java Main $input $ir",
]

